title: My blog
author: Rob Grossman
email: 
description: > # this means to ignore newlines until "baseurl:"
  Following my curiosity wherever it may lead.

# social links
twitter_username: # DO NOT include the @ character, or else the build will fail!
github_username:  digitalnomd # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
